In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
path = r'./datasets/U.S._Chronic_Disease_Indicators__CDI_.csv'

In [3]:
df = pd.read_csv(path)
df.head()

C:\Users\LENOVO\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (7,19,20,21,22,26,27,30,31,32,33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


YearStart  YearEnd LocationAbbr          LocationDesc DataSource    Topic  \
0       2013     2013           CA            California      YRBSS  Alcohol   
1       2013     2013           CO              Colorado      YRBSS  Alcohol   
2       2013     2013           CT           Connecticut      YRBSS  Alcohol   
3       2013     2013           DC  District of Columbia      YRBSS  Alcohol   
4       2013     2013           DE              Delaware      YRBSS  Alcohol   

                  Question Response DataValueUnit DataValueTypeID  ...  \
0  Alcohol use among youth      NaN             %         CrdPrev  ...   
1  Alcohol use among youth      NaN             %         CrdPrev  ...   
2  Alcohol use among youth      NaN             %         CrdPrev  ...   
3  Alcohol use among youth      NaN             %         CrdPrev  ...   
4  Alcohol use among youth      NaN             %         CrdPrev  ...   

  TopicID QuestionID  ResponseID LocationID StratificationCategoryID1  \
0     ALC     ALC1_1         NaN          6                   OVERALL   
1     ALC     ALC1_1         NaN          8                   OVERALL   
2     ALC     ALC1_1         NaN          9                   OVERALL   
3     ALC     ALC1_1         NaN         11                   OVERALL   
4     ALC     ALC1_1         NaN         10                   OVERALL   

   StratificationID1  StratificationCategoryID2 StratificationID2  \
0                OVR                        NaN               NaN   
1                OVR                        NaN               NaN   
2                OVR                        NaN               NaN   
3                OVR                        NaN               NaN   
4                OVR                        NaN               NaN   

  StratificationCategoryID3 StratificationID3  
0                       NaN               NaN  
1                       NaN               NaN  
2                       NaN               NaN  
3                       NaN               NaN  
4                       NaN               NaN  

[5 rows x 34 columns]

In [4]:
series = pd.Series((df.count()/len(df)) * 100)
series

YearStart                    100.000000
YearEnd                      100.000000
LocationAbbr                 100.000000
LocationDesc                 100.000000
DataSource                   100.000000
Topic                        100.000000
Question                     100.000000
Response                      32.717966
DataValueUnit                 86.240182
DataValueTypeID              100.000000
DataValueType                100.000000
DataValue                     79.598338
DataValueAlt                  69.757649
DataValueFootnoteSymbol       53.960523
DatavalueFootnote             53.883620
LowConfidenceLimit            59.416459
HighConfidenceLimit           59.416459
StratificationCategory1      100.000000
Stratification1              100.000000
StratificationCategory2       32.717966
Stratification2               32.717966
StratificationCategory3       32.717966
Stratification3               32.717966
GeoLocation                   99.395699
TopicID                      100.000000


In [5]:
series = series[series.values < 40]
series.index

Index(['Response', 'StratificationCategory2', 'Stratification2',
       'StratificationCategory3', 'Stratification3', 'ResponseID',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [6]:
df['Stratification2'].unique()

array([nan, ' '], dtype=object)

In [7]:
df.drop(columns=series.index,inplace =True)
df.head()

YearStart  YearEnd LocationAbbr          LocationDesc DataSource    Topic  \
0       2013     2013           CA            California      YRBSS  Alcohol   
1       2013     2013           CO              Colorado      YRBSS  Alcohol   
2       2013     2013           CT           Connecticut      YRBSS  Alcohol   
3       2013     2013           DC  District of Columbia      YRBSS  Alcohol   
4       2013     2013           DE              Delaware      YRBSS  Alcohol   

                  Question DataValueUnit DataValueTypeID     DataValueType  \
0  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
1  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
2  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
3  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
4  Alcohol use among youth             %         CrdPrev  Crude Prevalence   

   ... LowConfidenceLimit  HighConfidenceLimit StratificationCategory1  \
0  ...                NaN                  NaN                 Overall   
1  ...                NaN                  NaN                 Overall   
2  ...               32.7                 41.0                 Overall   
3  ...               30.2                 32.5                 Overall   
4  ...               33.7                 39.0                 Overall   

  Stratification1                                GeoLocation  TopicID  \
0         Overall   (37.63864012300047, -120.99999953799971)      ALC   
1         Overall  (38.843840757000464, -106.13361092099967)      ALC   
2         Overall    (41.56266102000046, -72.64984095199964)      ALC   
3         Overall                    (38.907192, -77.036871)      ALC   
4         Overall   (39.008830667000495, -75.57774116799965)      ALC   

  QuestionID LocationID StratificationCategoryID1 StratificationID1  
0     ALC1_1          6                   OVERALL               OVR  
1     ALC1_1          8                   OVERALL               OVR  
2     ALC1_1          9                   OVERALL               OVR  
3     ALC1_1         11                   OVERALL               OVR  
4     ALC1_1         10                   OVERALL               OVR  

[5 rows x 24 columns]

In [8]:
series1 = pd.Series((df.count()/len(df)) * 100)
series1

YearStart                    100.000000
YearEnd                      100.000000
LocationAbbr                 100.000000
LocationDesc                 100.000000
DataSource                   100.000000
Topic                        100.000000
Question                     100.000000
DataValueUnit                 86.240182
DataValueTypeID              100.000000
DataValueType                100.000000
DataValue                     79.598338
DataValueAlt                  69.757649
DataValueFootnoteSymbol       53.960523
DatavalueFootnote             53.883620
LowConfidenceLimit            59.416459
HighConfidenceLimit           59.416459
StratificationCategory1      100.000000
Stratification1              100.000000
GeoLocation                   99.395699
TopicID                      100.000000
QuestionID                   100.000000
LocationID                   100.000000
StratificationCategoryID1    100.000000
StratificationID1            100.000000
dtype: float64

In [9]:
series2 = series1[series1 < 87]
series2

DataValueUnit              86.240182
DataValue                  79.598338
DataValueAlt               69.757649
DataValueFootnoteSymbol    53.960523
DatavalueFootnote          53.883620
LowConfidenceLimit         59.416459
HighConfidenceLimit        59.416459
dtype: float64

In [10]:
df_low = df[series2.index]
df_low['DataValueUnit'].unique()

array(['%', nan, 'Number', 'cases per 100,000', '$', 'gallons',
       'cases per 10,000', 'cases per 1,000,000', 'per 100,000',
       'cases per 1,000', 'pack sales', 'Number ',
       'per 100,000 residents', 'Years'], dtype=object)

In [11]:
df_low[df_low['DataValue'].isna()]['DataValue']

0         NaN
1         NaN
9         NaN
12        NaN
20        NaN
         ... 
237956    NaN
237957    NaN
237958    NaN
237959    NaN
237960    NaN
Name: DataValue, Length: 48548, dtype: object

In [12]:
df_low['DataValueFootnoteSymbol']

0            -
1            -
2          NaN
3          NaN
4          NaN
          ... 
237956    ****
237957    ****
237958    ****
237959       -
237960       -
Name: DataValueFootnoteSymbol, Length: 237961, dtype: object

In [13]:
df.count()

YearStart                    237961
YearEnd                      237961
LocationAbbr                 237961
LocationDesc                 237961
DataSource                   237961
Topic                        237961
Question                     237961
DataValueUnit                205218
DataValueTypeID              237961
DataValueType                237961
DataValue                    189413
DataValueAlt                 165996
DataValueFootnoteSymbol      128405
DatavalueFootnote            128222
LowConfidenceLimit           141388
HighConfidenceLimit          141388
StratificationCategory1      237961
Stratification1              237961
GeoLocation                  236523
TopicID                      237961
QuestionID                   237961
LocationID                   237961
StratificationCategoryID1    237961
StratificationID1            237961
dtype: int64

In [14]:
len(df['DataValue'].unique())

16795

In [15]:
len(df['DataValueAlt'].unique())

16783

In [16]:
df.dropna(how='all',subset=['DataValue','DataValueAlt'],inplace=True)
df.head()

YearStart  YearEnd LocationAbbr          LocationDesc DataSource    Topic  \
2       2013     2013           CT           Connecticut      YRBSS  Alcohol   
3       2013     2013           DC  District of Columbia      YRBSS  Alcohol   
4       2013     2013           DE              Delaware      YRBSS  Alcohol   
5       2013     2013           FL               Florida      YRBSS  Alcohol   
6       2013     2013           GA               Georgia      YRBSS  Alcohol   

                  Question DataValueUnit DataValueTypeID     DataValueType  \
2  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
3  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
4  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
5  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
6  Alcohol use among youth             %         CrdPrev  Crude Prevalence   

   ... LowConfidenceLimit  HighConfidenceLimit StratificationCategory1  \
2  ...               32.7                 41.0                 Overall   
3  ...               30.2                 32.5                 Overall   
4  ...               33.7                 39.0                 Overall   
5  ...               33.1                 36.6                 Overall   
6  ...               23.8                 32.3                 Overall   

  Stratification1                               GeoLocation  TopicID  \
2         Overall   (41.56266102000046, -72.64984095199964)      ALC   
3         Overall                   (38.907192, -77.036871)      ALC   
4         Overall  (39.008830667000495, -75.57774116799965)      ALC   
5         Overall  (28.932040377000476, -81.92896053899966)      ALC   
6         Overall   (32.83968109300048, -83.62758034599966)      ALC   

  QuestionID LocationID StratificationCategoryID1 StratificationID1  
2     ALC1_1          9                   OVERALL               OVR  
3     ALC1_1         11                   OVERALL               OVR  
4     ALC1_1         10                   OVERALL               OVR  
5     ALC1_1         12                   OVERALL               OVR  
6     ALC1_1         13                   OVERALL               OVR  

[5 rows x 24 columns]

In [19]:
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'DataValueUnit', 'DataValueTypeID',
       'DataValueType', 'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'GeoLocation', 'TopicID',
       'QuestionID', 'LocationID', 'StratificationCategoryID1',
       'StratificationID1'],
      dtype='object')

In [26]:
len(df['LocationAbbr'].unique())

55

In [25]:
len(df['LocationDesc'].unique())

55

In [27]:
df['LocationID'].unique()

array([9, 11, 10, 12, 13, 66, 15, 16, 17, 20, 21, 22, 25, 24, 23, 26, 29,
       28, 30, 37, 38, 31, 33, 34, 35, 32, 36, 39, 40, 72, 44, 45, 46, 47,
       48, 59, 49, 51, 55, 54, 56, 5, 8, 27, 41, 42, 50, 53, 2, 1, 4, 6,
       19, 18, 78, '26', '27', '23', '29', '28', '30', '31', '37', '38',
       '48', '33', '34', '35', '39', '32', '36', '40', '49', '41', '51',
       '42', '72', '44', '45', '46', '47', '59', '50', '12', '53', '55',
       '54', '02', '56', '01', '04', '05', '06', '08', '09', '10', '11',
       '20', '13', '66', '15', '19', '16', '17', '18', '21', '22', '25',
       '24', 'US'], dtype=object)

In [28]:
df.drop(columns='LocationAbbr',inplace = True)
df.head()

YearStart  YearEnd          LocationDesc DataSource    Topic  \
2       2013     2013           Connecticut      YRBSS  Alcohol   
3       2013     2013  District of Columbia      YRBSS  Alcohol   
4       2013     2013              Delaware      YRBSS  Alcohol   
5       2013     2013               Florida      YRBSS  Alcohol   
6       2013     2013               Georgia      YRBSS  Alcohol   

                  Question DataValueUnit DataValueTypeID     DataValueType  \
2  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
3  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
4  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
5  Alcohol use among youth             %         CrdPrev  Crude Prevalence   
6  Alcohol use among youth             %         CrdPrev  Crude Prevalence   

  DataValue  ...  LowConfidenceLimit HighConfidenceLimit  \
2      36.7  ...                32.7                41.0   
3      31.4  ...                30.2                32.5   
4      36.3  ...                33.7                39.0   
5      34.8  ...                33.1                36.6   
6      27.9  ...                23.8                32.3   

  StratificationCategory1  Stratification1  \
2                 Overall          Overall   
3                 Overall          Overall   
4                 Overall          Overall   
5                 Overall          Overall   
6                 Overall          Overall   

                                GeoLocation TopicID QuestionID LocationID  \
2   (41.56266102000046, -72.64984095199964)     ALC     ALC1_1          9   
3                   (38.907192, -77.036871)     ALC     ALC1_1         11   
4  (39.008830667000495, -75.57774116799965)     ALC     ALC1_1         10   
5  (28.932040377000476, -81.92896053899966)     ALC     ALC1_1         12   
6   (32.83968109300048, -83.62758034599966)     ALC     ALC1_1         13   

  StratificationCategoryID1 StratificationID1  
2                   OVERALL               OVR  
3                   OVERALL               OVR  
4                   OVERALL               OVR  
5                   OVERALL               OVR  
6                   OVERALL               OVR  

[5 rows x 23 columns]

In [29]:
df.columns

Index(['YearStart', 'YearEnd', 'LocationDesc', 'DataSource', 'Topic',
       'Question', 'DataValueUnit', 'DataValueTypeID', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DatavalueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'GeoLocation', 'TopicID',
       'QuestionID', 'LocationID', 'StratificationCategoryID1',
       'StratificationID1'],
      dtype='object')

In [30]:
df['DataSource'].unique()

array(['YRBSS', 'PRAMS', 'Legal Research', 'BRFSS', 'NVSS',
       'State Inpatient Data', 'APIS', 'AEDS', 'Death certificate',
       'State Emergency Department Data',
       'Statewide central cancer registries',
       'United States Renal Data System', 'CMS Part A Claims Data',
       'STATE', 'Birth Certificate, NVSS', 'ACS 1-Year Estimates',
       'National Immunization Survey', 'mPINC',
       'CDC School Health Profiles',
       "CDC Children's Food Environment State Indicator Report",
       'CDC Breastfeeding Report Card', 'HRSA, UDS', 'InfoUSA; USDA',
       "USDA National Farmers' Market Directory", 'ASHW', 'CMS CCW',
       'NSCH', 'WFRS', 'Current Population Survey', 'NVSS, Mortality',
       'ACS 5-Year Estimates', 'ANRF'], dtype=object)

In [100]:
df.count()

YearStart                    140298
YearEnd                      140298
LocationDesc                 140298
DataSource                   140298
Topic                        140298
Question                     140298
DataValueUnit                140298
DataValueTypeID              140298
DataValue                    140298
DataValueAlt                 140298
LowConfidenceLimit           140298
HighConfidenceLimit          140298
StratificationCategory1      140298
Stratification1              140298
GeoLocation                  140298
TopicID                      140298
QuestionID                   140298
LocationID                   140298
StratificationCategoryID1    140298
StratificationID1            140298
dtype: int64

In [123]:
columns = ['Topic','DataValueAlt','Question','LocationDesc','Stratification1','StratificationCategory1']

In [34]:
df.dropna(how='all',subset=['GeoLocation'],inplace=True)

In [46]:
df['DataValueFootnoteSymbol'].value_counts()

     36819
#      306
Name: DataValueFootnoteSymbol, dtype: int64

In [49]:
36819+306

37125

In [48]:
df['DatavalueFootnote'].value_counts()

                                                                                                               36818
NSCH Data provided by Data Resource Center for Child and Adolescent Health.  Http://www.childhealthdata.org      203
NSCH Data provided by Data Resource Center for Child and Adolescent Health.  http://www.childhealthdata.org      103
Name: DatavalueFootnote, dtype: int64

In [50]:
36818+203+103

37124

In [41]:
df['LowConfidenceLimit'].unique()

array([ 32.7,  30.2,  33.7, ..., 885.5, 633.9, 428.6])

In [42]:
df['HighConfidenceLimit'].unique()

array([  41. ,   32.5,   39. , ...,  812.3,  561.6, 1786. ])

In [43]:
df.dropna(how = 'all',subset=['LowConfidenceLimit','HighConfidenceLimit'],inplace = True)

In [53]:
#df.drop(columns=['DatavalueFootnote','DataValueFootnoteSymbol'])

KeyError: "['DatavalueFootnote' 'DataValueFootnoteSymbol'] not found in axis"

In [65]:
df.head()

YearStart  YearEnd          LocationDesc DataSource    Topic  \
2       2013     2013           Connecticut      YRBSS  Alcohol   
3       2013     2013  District of Columbia      YRBSS  Alcohol   
4       2013     2013              Delaware      YRBSS  Alcohol   
5       2013     2013               Florida      YRBSS  Alcohol   
6       2013     2013               Georgia      YRBSS  Alcohol   

                  Question DataValueUnit DataValueTypeID DataValue  \
2  Alcohol use among youth             %         CrdPrev      36.7   
3  Alcohol use among youth             %         CrdPrev      31.4   
4  Alcohol use among youth             %         CrdPrev      36.3   
5  Alcohol use among youth             %         CrdPrev      34.8   
6  Alcohol use among youth             %         CrdPrev      27.9   

   DataValueAlt  LowConfidenceLimit  HighConfidenceLimit  \
2          36.7                32.7                 41.0   
3          31.4                30.2                 32.5   
4          36.3                33.7                 39.0   
5          34.8                33.1                 36.6   
6          27.9                23.8                 32.3   

  StratificationCategory1 Stratification1  \
2                 Overall         Overall   
3                 Overall         Overall   
4                 Overall         Overall   
5                 Overall         Overall   
6                 Overall         Overall   

                                GeoLocation TopicID QuestionID LocationID  \
2   (41.56266102000046, -72.64984095199964)     ALC     ALC1_1          9   
3                   (38.907192, -77.036871)     ALC     ALC1_1         11   
4  (39.008830667000495, -75.57774116799965)     ALC     ALC1_1         10   
5  (28.932040377000476, -81.92896053899966)     ALC     ALC1_1         12   
6   (32.83968109300048, -83.62758034599966)     ALC     ALC1_1         13   

  StratificationCategoryID1 StratificationID1  
2                   OVERALL               OVR  
3                   OVERALL               OVR  
4                   OVERALL               OVR  
5                   OVERALL               OVR  
6                   OVERALL               OVR

In [56]:
df[df['Topic'] == 'Alcohol']['DataValueUnit'].unique()

array(['%', 'Number', 'cases per 100,000'], dtype=object)

In [58]:
df.DataValueType.unique()

array(['Crude Prevalence', 'Age-adjusted Prevalence', 'Mean',
       'Age-adjusted Mean', 'Crude Rate', 'Age-adjusted Rate',
       'Average Annual Age-adjusted Rate', 'Average Annual Crude Rate',
       'Prevalence', 'Crude Mean', 'Percent', 'Median'], dtype=object)

In [59]:
df.DataValueTypeID.unique()

array(['CrdPrev', 'AgeAdjPrev', 'Mean', 'AgeAdjMean', 'CrdRate',
       'AgeAdjRate', 'AvgAnnAgeAdjRate', 'AvgAnnCrdRate', 'Prev',
       'CrdMean', 'Prct', 'Median'], dtype=object)

In [60]:
df.drop(columns='DataValueType',inplace=True)

In [117]:
len(df.Question.str.lower().unique())

164

In [96]:
len(df.QuestionID.unique())

163

In [92]:
len(df.LocationDesc.unique())

53

In [93]:
len(df.LocationID.unique())

53

In [122]:
len(df.Topic.str.lower().unique())

16

In [119]:
len(df.TopicID.unique())

16

In [81]:
len(df.Stratification1.unique())

10

In [80]:
len(df.StratificationID1.unique())

10

In [78]:
len(df.StratificationCategory1.unique())

3

In [79]:
len(df.StratificationCategoryID1.unique())

3

In [89]:
df['LocationID'] = df['LocationID'].map(lambda x : int(x))

In [98]:
df.YearStart.unique()

array([2013, 2011, 2014, 2012, 2010, 2008, 2009], dtype=int64)

In [99]:
df.YearEnd.unique()

array([2013, 2011, 2014, 2012, 2010], dtype=int64)

In [101]:
Series1 = pd.Series(df.DataValue)
Series2 = pd.Series(df.DataValueAlt)

In [108]:
len(Series2) == len(Series1)

True

In [111]:
Series1 = Series1.astype(np.float64)

In [114]:
np.sum(Series1.values == Series2.values) == len(Series1)

True

In [124]:
df.drop(columns=columns,inplace=True)

In [125]:
df.head()

YearStart  YearEnd DataSource DataValueUnit DataValueTypeID DataValue  \
2       2013     2013      YRBSS             %         CrdPrev      36.7   
3       2013     2013      YRBSS             %         CrdPrev      31.4   
4       2013     2013      YRBSS             %         CrdPrev      36.3   
5       2013     2013      YRBSS             %         CrdPrev      34.8   
6       2013     2013      YRBSS             %         CrdPrev      27.9   

   LowConfidenceLimit  HighConfidenceLimit  \
2                32.7                 41.0   
3                30.2                 32.5   
4                33.7                 39.0   
5                33.1                 36.6   
6                23.8                 32.3   

                                GeoLocation TopicID QuestionID  LocationID  \
2   (41.56266102000046, -72.64984095199964)     ALC     ALC1_1           9   
3                   (38.907192, -77.036871)     ALC     ALC1_1          11   
4  (39.008830667000495, -75.57774116799965)     ALC     ALC1_1          10   
5  (28.932040377000476, -81.92896053899966)     ALC     ALC1_1          12   
6   (32.83968109300048, -83.62758034599966)     ALC     ALC1_1          13   

  StratificationCategoryID1 StratificationID1  
2                   OVERALL               OVR  
3                   OVERALL               OVR  
4                   OVERALL               OVR  
5                   OVERALL               OVR  
6                   OVERALL               OVR

In [126]:
df.DataSource.unique()

array(['YRBSS', 'PRAMS', 'BRFSS', 'NVSS',
       'State Emergency Department Data', 'State Inpatient Data',
       'Statewide central cancer registries', 'Death certificate',
       'CMS Part A Claims Data', 'Birth Certificate, NVSS',
       'CDC School Health Profiles', 'NSCH'], dtype=object)

In [134]:
df['Geo_lat'] = df.GeoLocation.map(lambda x : x.split(',')[0][1:])

In [136]:
df['Geo_lon'] = df.GeoLocation.map(lambda x : x.split(',')[1][:-1])

In [142]:
df.head()

YearStart  YearEnd DataSource DataValueUnit DataValueTypeID  DataValue  \
2       2013     2013      YRBSS             %         CrdPrev       36.7   
3       2013     2013      YRBSS             %         CrdPrev       31.4   
4       2013     2013      YRBSS             %         CrdPrev       36.3   
5       2013     2013      YRBSS             %         CrdPrev       34.8   
6       2013     2013      YRBSS             %         CrdPrev       27.9   

   LowConfidenceLimit  HighConfidenceLimit  \
2                32.7                 41.0   
3                30.2                 32.5   
4                33.7                 39.0   
5                33.1                 36.6   
6                23.8                 32.3   

                                GeoLocation TopicID QuestionID  LocationID  \
2   (41.56266102000046, -72.64984095199964)     ALC     ALC1_1           9   
3                   (38.907192, -77.036871)     ALC     ALC1_1          11   
4  (39.008830667000495, -75.57774116799965)     ALC     ALC1_1          10   
5  (28.932040377000476, -81.92896053899966)     ALC     ALC1_1          12   
6   (32.83968109300048, -83.62758034599966)     ALC     ALC1_1          13   

  StratificationCategoryID1 StratificationID1    Geo_lat    Geo_lon  
2                   OVERALL               OVR  41.562661 -72.649841  
3                   OVERALL               OVR  38.907192 -77.036871  
4                   OVERALL               OVR  39.008831 -75.577741  
5                   OVERALL               OVR  28.932040 -81.928961  
6                   OVERALL               OVR  32.839681 -83.627580

In [143]:
df.dtypes #DataValue,

YearStart                      int64
YearEnd                        int64
DataSource                    object
DataValueUnit                 object
DataValueTypeID               object
DataValue                    float64
LowConfidenceLimit           float64
HighConfidenceLimit          float64
GeoLocation                   object
TopicID                       object
QuestionID                    object
LocationID                     int64
StratificationCategoryID1     object
StratificationID1             object
Geo_lat                      float64
Geo_lon                      float64
dtype: object

In [139]:
df['DataValue'] = df.DataValue.astype(np.float64)

In [141]:
df['Geo_lat'] = df.Geo_lat.astype(np.float64)
df['Geo_lon'] = df.Geo_lon.astype(np.float64)